
package com.banking.user_service.enums;

public enum AuditAction {
    USER_REGISTRATION,
    EMAIL_VERIFIED,
    PHONE_REGISTERED,
    PHONE_VERIFIED,
    MPIN_CREATED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    MPIN_LOCKED,
    MPIN_RESET,
    PROFILE_UPDATE,
    CONTACT_UPDATE,
    ADDRESS_UPDATED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_SUSPENDED,
    ROLE_CHANGED,
    KYC_SUBMITTED,
    KYC_APPROVED,
    KYC_REJECTED
}